version: '2'
services:
    jhipster_i18n-app:
        image: jhipster_i18n
        external_links:
            - jhipster_i18n-postgresql:postgresql
            - jhipster_i18n-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/jhipster_i18n
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    jhipster_i18n-postgresql:
        extends:
            file: postgresql.yml
            service: jhipster_i18n-postgresql
    jhipster_i18n-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipster_i18n-elasticsearch
